spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.249/sell_cloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.199.249
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev3
girl:
  name: yatou
  age: 201
