spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.199.249/sell_cloud?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
  redis:
    host: 192.168.199.249
    port: 6379
